ci/tests.yml: added .shell-unit-tests job template
Signed-off-by: Felix Kühnl <felix.kuehnl@tq-group.com>

diff --git a/ci/tests.yml b/ci/tests.yml
--- a/ci/tests.yml
+++ b/ci/tests.yml
@@ -49,3 +49,15 @@
     - .image-test
   script:
     - lint.sh shell
+
+.shell-unit-tests:
+  stage: test
+  extends:
+    - .gitlab-runner-tag
+    - .image-test
+  script:
+    - >
+        for test_file in $(find . -type f -name '*_test.sh' | sort); do
+        echo "*** Running Shell test $test_file ***";
+        "./$test_file" && echo 'success' || { echo 'FAILED' && false; };
+        done
